/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author dam2_alu05@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {

    private static final int ALTO_IMAGEN_CENTRAL = 650;
    private static final int ANCHO_IMAGEN_CENTRAL = 550;
    private static final int POSX_CENTRAL_IMAGE = 720;
    private static final int POSY_CENTRAL_IMAGE =250;
    private static final int POSYPANELS = 310;
    private static final int POSXPANELPJS = 93;
    private static final int POSXPANELHABILITIS = 1210;
    
    private JButton actualPj = new JButton();
    /**
     * Creates new form Screen
     */
    public MainJFrame() {
        initComponents();
        setLayout();
        quitBackgroundColorPanelCuadricula();
        this.displayImagePJ.setLayout(null);
        //maximizeWindow();
        quitLayoutLateral();
        modifyInitComponents();
        this.enableDisableButtonsAddEditCreateVisible(true);
        this.enableDisableRegisterLoginButtons(false);
        
        this.setFondo();
        this.setColor();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        roleComboBoxItem = new javax.swing.JComboBox<>();
        registerJButton = new javax.swing.JButton();
        loginJButton = new javax.swing.JButton();
        panelHabilitis = new javax.swing.JPanel();
        descripcionLabel = new javax.swing.JLabel();
        habilidadesLabel = new javax.swing.JLabel();
        imagenhabilidad1Label = new javax.swing.JLabel();
        nombrehabilidad1Label = new javax.swing.JLabel();
        descripcionhabilidad1Label = new javax.swing.JLabel();
        imagenhabilidad2Label = new javax.swing.JLabel();
        nombrehabilidad2Label = new javax.swing.JLabel();
        descripcionhabilidad2Label = new javax.swing.JLabel();
        imagenhabilidad3Label = new javax.swing.JLabel();
        nombrehabilidad3Label = new javax.swing.JLabel();
        descripcionhabilidad3Label = new javax.swing.JLabel();
        imagenhabilidad4Label = new javax.swing.JLabel();
        nombrehabilidad4Label = new javax.swing.JLabel();
        descripcionhabilidad4Label = new javax.swing.JLabel();
        descriptionTextLabel = new javax.swing.JLabel();
        panelPjs = new javax.swing.JPanel();
        displayImagePJ = new javax.swing.JLabel();
        CreatePJButton = new javax.swing.JButton();
        EditPJButton = new javax.swing.JButton();
        DelPJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setExtendedState(this.MAXIMIZED_BOTH);

        titleJLabel.setFont(new java.awt.Font("Inter Regular", 1, 36)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("ValorantApi");

        searchTextField.setToolTipText("Escribe el agente a buscar");
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        roleComboBoxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rol" }));

        registerJButton.setText("Registrarse");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });

        loginJButton.setText("Login");

        panelHabilitis.setBackground(new java.awt.Color(0, 255, 0));

        descripcionLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        descripcionLabel.setText("Descripcion");

        habilidadesLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        habilidadesLabel.setText("Habilidades");

        imagenhabilidad1Label.setText("");

        nombrehabilidad1Label.setText("");

        descripcionhabilidad1Label.setText("");

        imagenhabilidad2Label.setText("");

        nombrehabilidad2Label.setText("");

        descripcionhabilidad2Label.setText("");

        imagenhabilidad3Label.setText("");

        nombrehabilidad3Label.setText("");

        descripcionhabilidad3Label.setText("");

        imagenhabilidad4Label.setText("");

        nombrehabilidad4Label.setText("");

        descripcionhabilidad4Label.setText("");

        descriptionTextLabel.setText("");

        javax.swing.GroupLayout panelHabilitisLayout = new javax.swing.GroupLayout(panelHabilitis);
        panelHabilitis.setLayout(panelHabilitisLayout);
        panelHabilitisLayout.setHorizontalGroup(
            panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabilitisLayout.createSequentialGroup()
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(descripcionLabel))
                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(descriptionTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panelHabilitisLayout.createSequentialGroup()
                                .addComponent(imagenhabilidad4Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombrehabilidad4Label))
                            .addGroup(panelHabilitisLayout.createSequentialGroup()
                                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imagenhabilidad1Label)
                                    .addComponent(imagenhabilidad2Label))
                                .addGap(35, 35, 35)
                                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nombrehabilidad1Label)
                                    .addComponent(nombrehabilidad2Label)))
                            .addGroup(panelHabilitisLayout.createSequentialGroup()
                                .addComponent(imagenhabilidad3Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nombrehabilidad3Label)))
                        .addGap(52, 52, 52)
                        .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionhabilidad2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(descripcionhabilidad3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(panelHabilitisLayout.createSequentialGroup()
                                .addComponent(descripcionhabilidad1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(descripcionhabilidad4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(288, 288, 288))
            .addGroup(panelHabilitisLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(habilidadesLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelHabilitisLayout.setVerticalGroup(
            panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabilitisLayout.createSequentialGroup()
                .addComponent(descripcionLabel)
                .addGap(18, 18, 18)
                .addComponent(descriptionTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(habilidadesLabel)
                .addGap(3, 3, 3)
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenhabilidad1Label)
                    .addComponent(nombrehabilidad1Label)
                    .addComponent(descripcionhabilidad1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionhabilidad2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrehabilidad2Label)
                    .addComponent(imagenhabilidad2Label))
                .addGap(31, 31, 31)
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionhabilidad3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrehabilidad3Label)
                    .addComponent(imagenhabilidad3Label))
                .addGap(30, 30, 30)
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descripcionhabilidad4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombrehabilidad4Label)
                    .addComponent(imagenhabilidad4Label))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        panelPjs.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout panelPjsLayout = new javax.swing.GroupLayout(panelPjs);
        panelPjs.setLayout(panelPjsLayout);
        panelPjsLayout.setHorizontalGroup(
            panelPjsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        panelPjsLayout.setVerticalGroup(
            panelPjsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 707, Short.MAX_VALUE)
        );

        displayImagePJ.setText("");

        CreatePJButton.setText("Crear");

        EditPJButton.setText("Editar");
        EditPJButton.setEnabled(false);

        DelPJButton.setText("Del");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(panelPjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(roleComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(displayImagePJ, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CreatePJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EditPJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DelPJButton)
                        .addGap(108, 108, 108)
                        .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerJButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelHabilitis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92))))
            .addGroup(layout.createSequentialGroup()
                .addGap(539, 539, 539)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 808, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerJButton)
                    .addComponent(loginJButton)
                    .addComponent(CreatePJButton)
                    .addComponent(EditPJButton)
                    .addComponent(DelPJButton))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelHabilitis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelPjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(displayImagePJ, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(347, 347, 347))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addSetImageDisplayLabel(ImageIcon icon) {

        quitLayoutLateral();
        Image image = icon.getImage();

        //Tratamiento Imagen
        Image imageRedimensity = image.getScaledInstance(ANCHO_IMAGEN_CENTRAL, ALTO_IMAGEN_CENTRAL, Image.SCALE_SMOOTH);

        // Creacion  ImageIcon redimensionado
        ImageIcon imagenBotonFinal = new ImageIcon(imageRedimensity);

        if (this.displayImagePJ != null) {
            this.displayImagePJ.setIcon(imagenBotonFinal);
        } else {
            this.displayImagePJ.setIcon(null);
            this.displayImagePJ.setIcon(imagenBotonFinal);
        }
    }

    private void quitLayoutLateral() {
        this.displayImagePJ.setBounds(POSX_CENTRAL_IMAGE, POSY_CENTRAL_IMAGE, ANCHO_IMAGEN_CENTRAL, ALTO_IMAGEN_CENTRAL);
    }

    private void setLayout() {
        panelPjs.setBounds(POSXPANELPJS, POSYPANELS, 1100, 1100);
        panelHabilitis.setBounds(POSXPANELHABILITIS, POSYPANELS, 1100, 1100);
        //posicionEtiquetasPanelHabilitis();
        panelHabilitis.setVisible(true);
        panelPjs.setVisible(true);  
    }

   
    
    
    private void modifyInitComponents() {
        this.setLayout(null);
        maximizeWindow(); 
    }
    
    public void clearPanelPj(){
        this.panelPjs.removeAll();
        this.revalidate();
        this.repaint();
    }
    
    public List<JButton> getButtonsPanelPjs(){
        List<JButton> listaBotones = new ArrayList<>();
        for(Component component : this.panelPjs.getComponents()){
            if(component instanceof JButton){
                JButton boton = (JButton) component;
                listaBotones.add(boton);
            }
        }
        
        return listaBotones;
    }
    
    public void saveActualPj(JButton boton){
        this.actualPj = boton;
    }
    
    public String getActualPj(){
        return this.actualPj.getName();
    }
    
    public void enableEditJButton(){
        this.EditPJButton.setEnabled(true);
    }
    
    public void disableEditJButton(){
        this.EditPJButton.setEnabled(false);
    }

    public void addButtonPj(JButton button) {
        this.panelPjs.add(button);
    }

    public void setPanel(JPanel panel) {
        this.panelPjs = panel;
    }

    public void setImageTitle(ImageIcon icon) {
        this.titleJLabel.setText(null);
        this.titleJLabel.setIcon(icon);

        // X Y ANCHO ALTO
        this.titleJLabel.setVisible(true);
    }
    
    private void quitBackgroundColorPanelCuadricula() {
        this.panelPjs.setBackground(null);
        //Set opaque aplica que herede o color do pai, neste caso JFrame
        this.panelPjs.setOpaque(false);
        this.panelHabilitis.setBackground(null);
        this.panelHabilitis.setOpaque(false);
    }

    private void maximizeWindow() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        this.setLocation(0, 0);
    }

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJButtonActionPerformed

    public void addItemRoleComboBox(String item) {
        this.roleComboBoxItem.addItem(item);
    }
    
    public void setRegisterJButtonActionListener(ActionListener al) {
        this.registerJButton.addActionListener(al);
    }

    public void setLoginJButtonActionListener(ActionListener al) {
        this.loginJButton.addActionListener(al);
    }
    
    public void setSearchTextFieldKeyListener(KeyListener kl){
        this.searchTextField.addKeyListener(kl);
    }
    
    public void setRoleComboJComboBoxActionListener(ActionListener al){
        this.roleComboBoxItem.addActionListener(al);
    }

    public String getSearchTextField() {
        return searchTextField.getText();
    }
    
    public Object getItemRoleComboJComboBox(){
        return this.roleComboBoxItem.getSelectedItem();
    }

    public void setSearchTextField(String search) {
        searchTextField.setText(search);
    }

    public void setImagenhabilidad1Label(ImageIcon icon) {
        this.imagenhabilidad1Label.setIcon(icon);
    }

    public void setNombrehabilidad1Label(String text) {
        this.nombrehabilidad1Label.setText(text);
    }
    
    public void setDescripcionPersonajeLabel(String text){
        this.descriptionTextLabel.setText(text);
    }

    public void setDescripcionhabilidad1Label(String text) {
        this.descripcionhabilidad1Label.setText(text);
    }

    public void setImagenhabilidad2Label(ImageIcon icon) {
        this.imagenhabilidad2Label.setIcon(icon);
    }

    public void setNombrehabilidad2Label(String text) {
        this.nombrehabilidad2Label.setText(text);
    }

    public void setDescripcionhabilidad2Label(String text) {
        this.descripcionhabilidad2Label.setText(text);
    }

    public void setImagenhabilidad3Label(ImageIcon icon) {
        this.imagenhabilidad3Label.setIcon(icon);
    }

    public void setNombrehabilidad3Label(String text) {
        this.nombrehabilidad3Label.setText(text);
    }

    public void setDescripcionhabilidad3Label(String text) {
        this.descripcionhabilidad3Label.setText(text);
    }

    public void setImagenhabilidad4Label(ImageIcon icon) {
        this.imagenhabilidad4Label.setIcon(icon);
    }

    public void setNombrehabilidad4Label(String text) {
        this.nombrehabilidad4Label.setText(text);
    }

    public void setDescripcionhabilidad4Label(String text) {
        this.descripcionhabilidad4Label.setText(text);
    }
    
    public JLabel getImagenhabilidad1Label() {
        return this.imagenhabilidad1Label;
    }

    public JLabel getImagenhabilidad2Label() {
        return this.imagenhabilidad2Label;
    }

    public JLabel getImagenhabilidad3Label() {
        return this.imagenhabilidad3Label;
    }

    public JLabel getImagenhabilidad4Label() {
        return this.imagenhabilidad4Label;
    }
    
    public void setDelPjActionListener(ActionListener al){
        this.DelPJButton.addActionListener(al);
    }
    public void setEditPjActionListener(ActionListener al){
        this.EditPJButton.addActionListener(al);
    }
    public void setCreatePjActionListener(ActionListener al){
        this.CreatePJButton.addActionListener(al);
    }
    public void enableDisableButtonsAddEditCreateVisible(Boolean enableDisable){
        this.CreatePJButton.setVisible(enableDisable);
        this.DelPJButton.setVisible(enableDisable);
        this.EditPJButton.setVisible(enableDisable);
    }
    public void enableDisableRegisterLoginButtons(Boolean enableDisable){
        this.registerJButton.setVisible(enableDisable);
        this.loginJButton.setVisible(enableDisable);
    }
    
    public void setFondo() {

        this.getContentPane().createImage(WIDTH, HEIGHT);
    }

    public void setColor() {

        this.getContentPane().setBackground(new Color(195,0,0));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatePJButton;
    private javax.swing.JButton DelPJButton;
    private javax.swing.JButton EditPJButton;
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JLabel descripcionhabilidad1Label;
    private javax.swing.JLabel descripcionhabilidad2Label;
    private javax.swing.JLabel descripcionhabilidad3Label;
    private javax.swing.JLabel descripcionhabilidad4Label;
    private javax.swing.JLabel descriptionTextLabel;
    private javax.swing.JLabel displayImagePJ;
    private javax.swing.JLabel habilidadesLabel;
    private javax.swing.JLabel imagenhabilidad1Label;
    private javax.swing.JLabel imagenhabilidad2Label;
    private javax.swing.JLabel imagenhabilidad3Label;
    private javax.swing.JLabel imagenhabilidad4Label;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel nombrehabilidad1Label;
    private javax.swing.JLabel nombrehabilidad2Label;
    private javax.swing.JLabel nombrehabilidad3Label;
    private javax.swing.JLabel nombrehabilidad4Label;
    private javax.swing.JPanel panelHabilitis;
    private javax.swing.JPanel panelPjs;
    private javax.swing.JButton registerJButton;
    private javax.swing.JComboBox<String> roleComboBoxItem;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables

    
    

}
