/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author dam2_alu05@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {

    private static final int ALTO_IMAGEN_CENTRAL = 650;
    private static final int ANCHO_IMAGEN_CENTRAL = 550;
    private static final int POSX_CENTRAL_IMAGE = 750;
    private static final int POSY_CENTRAL_IMAGE =280;      

    /**
     * Creates new form Screen
     */
    public MainJFrame() {
        initComponents();
        setLayout();
        quitBackgroundColorPanelCuadricula();
        this.displayImagePJ.setLayout(null);
        maximizeWindow();
        quitLayoutLateral();
        
        modifyInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleJLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        roleComboBoxItem = new javax.swing.JComboBox<>();
        registerJButton = new javax.swing.JButton();
        loginJButton = new javax.swing.JButton();
        panelHabilitis = new javax.swing.JPanel();
        descripcionLabel = new javax.swing.JLabel();
        habilidadesLabel = new javax.swing.JLabel();
        imagenhabilidad1Label = new javax.swing.JLabel();
        nombrehabilidad1Label = new javax.swing.JLabel();
        descripcionhabilidad1Label = new javax.swing.JLabel();
        imagenhabilidad2Label = new javax.swing.JLabel();
        nombrehabilidad2Label = new javax.swing.JLabel();
        descripcionhabilidad2Label = new javax.swing.JLabel();
        imagenhabilidad3Label = new javax.swing.JLabel();
        nombrehabilidad3Label = new javax.swing.JLabel();
        descripcionhabilidad3Label = new javax.swing.JLabel();
        imagenhabilidad4Label = new javax.swing.JLabel();
        nombrehabilidad4Label = new javax.swing.JLabel();
        descripcionhabilidad4Label = new javax.swing.JLabel();
        descriptionTextLabel = new javax.swing.JLabel();
        panelPjs = new javax.swing.JPanel();
        displayImagePJ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(this.MAXIMIZED_BOTH);

        titleJLabel.setFont(new java.awt.Font("Inter Regular", 1, 36)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleJLabel.setText("ValorantApi");

        searchTextField.setToolTipText("Escribe el agente a buscar");
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        roleComboBoxItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rol" }));

        registerJButton.setText("Registrarse");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });

        loginJButton.setText("Login");

        panelHabilitis.setBackground(new java.awt.Color(0, 255, 0));

        descripcionLabel.setText("Descripcion");

        habilidadesLabel.setText("Habilidades");

        imagenhabilidad1Label.setText("");

        nombrehabilidad1Label.setText("");

        descripcionhabilidad1Label.setText("");

        imagenhabilidad2Label.setText("");

        nombrehabilidad2Label.setText("");

        descripcionhabilidad2Label.setText("");

        imagenhabilidad3Label.setText("");

        nombrehabilidad3Label.setText("");

        descripcionhabilidad3Label.setText("");

        imagenhabilidad4Label.setText("");

        nombrehabilidad4Label.setText("");

        descripcionhabilidad4Label.setText("");

        descriptionTextLabel.setText("");

        javax.swing.GroupLayout panelHabilitisLayout = new javax.swing.GroupLayout(panelHabilitis);
        panelHabilitis.setLayout(panelHabilitisLayout);
        panelHabilitisLayout.setHorizontalGroup(
            panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabilitisLayout.createSequentialGroup()
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHabilitisLayout.createSequentialGroup()
                                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(imagenhabilidad1Label)
                                    .addComponent(imagenhabilidad2Label)
                                    .addComponent(imagenhabilidad3Label)
                                    .addComponent(imagenhabilidad4Label))
                                .addGap(18, 18, 18)
                                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                                        .addComponent(nombrehabilidad4Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(descripcionhabilidad4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                                        .addComponent(nombrehabilidad2Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(descripcionhabilidad2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                                        .addComponent(nombrehabilidad1Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(descripcionhabilidad1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                                        .addComponent(nombrehabilidad3Label)
                                        .addGap(18, 18, 18)
                                        .addComponent(descripcionhabilidad3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(descriptionTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(habilidadesLabel))
                    .addGroup(panelHabilitisLayout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(descripcionLabel)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        panelHabilitisLayout.setVerticalGroup(
            panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHabilitisLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(descripcionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(habilidadesLabel)
                .addGap(18, 18, 18)
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenhabilidad1Label)
                    .addComponent(nombrehabilidad1Label)
                    .addComponent(descripcionhabilidad1Label))
                .addGap(30, 30, 30)
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenhabilidad2Label)
                    .addComponent(nombrehabilidad2Label)
                    .addComponent(descripcionhabilidad2Label))
                .addGap(34, 34, 34)
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenhabilidad3Label)
                    .addComponent(nombrehabilidad3Label)
                    .addComponent(descripcionhabilidad3Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 408, Short.MAX_VALUE)
                .addGroup(panelHabilitisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenhabilidad4Label)
                    .addComponent(nombrehabilidad4Label)
                    .addComponent(descripcionhabilidad4Label))
                .addGap(18, 18, 18))
        );

        panelPjs.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout panelPjsLayout = new javax.swing.GroupLayout(panelPjs);
        panelPjs.setLayout(panelPjsLayout);
        panelPjsLayout.setHorizontalGroup(
            panelPjsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 691, Short.MAX_VALUE)
        );
        panelPjsLayout.setVerticalGroup(
            panelPjsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        displayImagePJ.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(panelPjs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(roleComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(displayImagePJ, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(panelHabilitis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 458, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerJButton)
                        .addGap(33, 33, 33)
                        .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(414, 414, 414))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roleComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerJButton)
                    .addComponent(loginJButton))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelPjs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelHabilitis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(displayImagePJ, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(347, 347, 347))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void addSetImageDisplayLabel(ImageIcon icon) {

        quitLayoutLateral();
        Image image = icon.getImage();

        //Tratamiento Imagen
        Image imageRedimensity = image.getScaledInstance(ANCHO_IMAGEN_CENTRAL, ALTO_IMAGEN_CENTRAL, Image.SCALE_SMOOTH);

        // Creacion  ImageIcon redimensionado
        ImageIcon imagenBotonFinal = new ImageIcon(imageRedimensity);

        if (this.displayImagePJ != null) {
            this.displayImagePJ.setIcon(imagenBotonFinal);
        } else {
            this.displayImagePJ.setIcon(null);
            this.displayImagePJ.setIcon(imagenBotonFinal);
        }

    }

    private void quitLayoutLateral() {
        // Pruebas sin layout
        //this.displayImagePJ.setLayout(null);
        //this.grandImagePJ.setOpaque(false);
        this.displayImagePJ.setBounds(POSX_CENTRAL_IMAGE, POSY_CENTRAL_IMAGE, ANCHO_IMAGEN_CENTRAL, ALTO_IMAGEN_CENTRAL);
        // x y ancho alto
    }

    private void setLayout() {

        panelPjs.setBounds(0, 0, 1100, 1100);
        panelHabilitis.setBounds(0, 0, 1100, 1100);

        panelHabilitis.setVisible(true);
        panelPjs.setVisible(true);
        //this.setSize(1100, 1000);

    }

    public void addButtonPj(JButton button) {
        this.panelPjs.add(button);
    }

    public void addItemRoleComboBox(String item) {
        this.roleComboBoxItem.addItem(item);
    }

    public void setPanel(JPanel panel) {
        this.panelPjs = panel;
    }

    public void setImageTitle(ImageIcon icon) {
        this.titleJLabel.setText(null);
        this.titleJLabel.setIcon(icon);

        // X Y ANCHO ALTO
        this.titleJLabel.setVisible(true);
    }

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJButtonActionPerformed

    public void setRegisterJButtonActionListener(ActionListener al) {
        this.registerJButton.addActionListener(al);
    }

    public void setLoginJButtonActionListener(ActionListener al) {
        this.loginJButton.addActionListener(al);
    }

    public String getSearchTextField() {
        return searchTextField.getText();
    }

    public void setSearchTextField(String search) {
        searchTextField.setText(search);
    }

    public void setImagenhabilidad1Label(ImageIcon icon) {
        this.imagenhabilidad1Label.setIcon(icon);
    }

    public void setNombrehabilidad1Label(String text) {
        this.nombrehabilidad1Label.setText(text);
    }

    public void setDescripcionhabilidad1Label(String text) {
        this.descripcionhabilidad1Label.setText(text);
    }

    public void setImagenhabilidad2Label(ImageIcon icon) {
        this.imagenhabilidad2Label.setIcon(icon);
    }

    public void setNombrehabilidad2Label(String text) {
        this.nombrehabilidad2Label.setText(text);
    }

    public void setDescripcionhabilidad2Label(String text) {
        this.descripcionhabilidad2Label.setText(text);
    }

    public void setImagenhabilidad3Label(ImageIcon icon) {
        this.imagenhabilidad3Label.setIcon(icon);
    }

    public void setNombrehabilidad3Label(String text) {
        this.nombrehabilidad3Label.setText(text);
    }

    public void setDescripcionhabilidad3Label(String text) {
        this.descripcionhabilidad3Label.setText(text);
    }

    public void setImagenhabilidad4Label(ImageIcon icon) {
        this.imagenhabilidad4Label.setIcon(icon);
    }

    public void setNombrehabilidad4Label(String text) {
        this.nombrehabilidad4Label.setText(text);
    }

    public void setDescripcionhabilidad4Label(String text) {
        this.descripcionhabilidad4Label.setText(text);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JLabel descripcionhabilidad1Label;
    private javax.swing.JLabel descripcionhabilidad2Label;
    private javax.swing.JLabel descripcionhabilidad3Label;
    private javax.swing.JLabel descripcionhabilidad4Label;
    private javax.swing.JLabel descriptionTextLabel;
    private javax.swing.JLabel displayImagePJ;
    private javax.swing.JLabel habilidadesLabel;
    private javax.swing.JLabel imagenhabilidad1Label;
    private javax.swing.JLabel imagenhabilidad2Label;
    private javax.swing.JLabel imagenhabilidad3Label;
    private javax.swing.JLabel imagenhabilidad4Label;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel nombrehabilidad1Label;
    private javax.swing.JLabel nombrehabilidad2Label;
    private javax.swing.JLabel nombrehabilidad3Label;
    private javax.swing.JLabel nombrehabilidad4Label;
    private javax.swing.JPanel panelHabilitis;
    private javax.swing.JPanel panelPjs;
    private javax.swing.JButton registerJButton;
    private javax.swing.JComboBox<String> roleComboBoxItem;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JLabel titleJLabel;
    // End of variables declaration//GEN-END:variables

    private void quitBackgroundColorPanelCuadricula() {
        this.panelPjs.setBackground(null);
        //Set opaque aplica que herede o color do pai, neste caso JFrame
        this.panelPjs.setOpaque(false);
        this.panelHabilitis.setBackground(null);
        this.panelHabilitis.setOpaque(false);
    }

    private void maximizeWindow() {
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize);
        this.setLocation(0, 0);

    }

    public JLabel getImagenhabilidad1Label() {
        return this.imagenhabilidad1Label;
    }

    public JLabel getImagenhabilidad2Label() {
        return this.imagenhabilidad2Label;
    }

    public JLabel getImagenhabilidad3Label() {
        return this.imagenhabilidad3Label;
    }

    public JLabel getImagenhabilidad4Label() {
        return this.imagenhabilidad4Label;
    }

    private void modifyInitComponents() {
        

        this.setLayout(null);
        maximizeWindow();
        
        
    }

}
