/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.user;

import java.awt.event.ActionListener;
import java.util.Arrays;

/**
 *
 * @author Christian
 */
public class UserJDialog extends javax.swing.JDialog {

    /**
     * Creates new form UserJDialog
     */
    public UserJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userLoginLabel = new javax.swing.JLabel();
        passwordJLabel = new javax.swing.JLabel();
        loginJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        loginUserJTextField = new javax.swing.JTextField();
        logintTitleJLabel = new javax.swing.JLabel();
        passwordTextField = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        userLoginLabel.setText("Usuario");

        passwordJLabel.setText("Password");

        loginJButton.setText("Login");

        cancelJButton.setText("Cancelar");

        loginUserJTextField.setText("");

        logintTitleJLabel.setText("Login");

        passwordTextField.setText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(userLoginLabel)
                                .addGap(18, 18, 18)
                                .addComponent(loginUserJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(passwordJLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordTextField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(loginJButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cancelJButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(logintTitleJLabel)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(logintTitleJLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLoginLabel)
                    .addComponent(loginUserJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordJLabel)
                    .addComponent(passwordTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginJButton)
                    .addComponent(cancelJButton))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setCancelJButtonActionListener(ActionListener al){
      this.cancelJButton.addActionListener(al);
    }
    
    public void setLoginJButtonActionListener(ActionListener al){
      this.loginJButton.addActionListener(al);
    }
    
    public void setTextLoginJButton(String text){
        this.loginJButton.setText(text);
    }
    
    public void setTextLoginTitleJLabel(String text){
        this.logintTitleJLabel.setText(text);
    }
    
    public String getTextUserJTextField(){
        return loginUserJTextField.getText();
    }
    
    public String getTextPasswordJTextField(){
        char[] passwordChars = passwordTextField.getPassword();
        return String.copyValueOf(passwordChars);
    }
    
    public void clearFields(){
        this.loginUserJTextField.setText("");
        this.passwordTextField.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JButton loginJButton;
    private javax.swing.JTextField loginUserJTextField;
    private javax.swing.JLabel logintTitleJLabel;
    private javax.swing.JLabel passwordJLabel;
    private javax.swing.JPasswordField passwordTextField;
    private javax.swing.JLabel userLoginLabel;
    // End of variables declaration//GEN-END:variables
}
