/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.modifyPjs;

import java.awt.Dimension;
 import java.awt.event.ActionListener;
import javax.swing.JTextField;

/**
 *
 * @author Christian
 */
public class CreateAndEditPJDialog extends javax.swing.JDialog {    
    public CreateAndEditPJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        fixJTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createAgentJLabel = new javax.swing.JLabel();
        nombrePJLabel = new javax.swing.JLabel();
        descriptionPJLabel = new javax.swing.JLabel();
        imageIconJLabel = new javax.swing.JLabel();
        roleJLabel = new javax.swing.JLabel();
        imagenCuerpoEnteroJLabel = new javax.swing.JLabel();
        nameAgentJTextField = new javax.swing.JTextField();
        descriptionAgenJTextField = new javax.swing.JTextField();
        iconJTextField = new javax.swing.JTextField();
        roleJTextField = new javax.swing.JTextField();
        imageCuerpoEnteroJTextField = new javax.swing.JTextField();
        habilitiesJLabel = new javax.swing.JLabel();
        hability1JLabel = new javax.swing.JLabel();
        hability2JLabel = new javax.swing.JLabel();
        hability3JLabel = new javax.swing.JLabel();
        hability4JLabel = new javax.swing.JLabel();
        nameHabilidad1 = new javax.swing.JLabel();
        descriptionHabilidad1 = new javax.swing.JLabel();
        descriptionHabilidad2 = new javax.swing.JLabel();
        nameHabilidad2 = new javax.swing.JLabel();
        nameHabilidad3 = new javax.swing.JLabel();
        descriptionHabilidad3 = new javax.swing.JLabel();
        nameHabilidad4 = new javax.swing.JLabel();
        descriptionHabilidad4 = new javax.swing.JLabel();
        nameHability1JTextField = new javax.swing.JTextField();
        nameHability3JTextField = new javax.swing.JTextField();
        nameHability2JTextField = new javax.swing.JTextField();
        nameHability4JTextField = new javax.swing.JTextField();
        descriptionHability1JTextField = new javax.swing.JTextField();
        descriptionHability2JTextField = new javax.swing.JTextField();
        descriptionHability3JTextField = new javax.swing.JTextField();
        descriptionHability4JTextField = new javax.swing.JTextField();
        createJButton = new javax.swing.JButton();
        cancelJButton = new javax.swing.JButton();
        plantillaJLabel = new javax.swing.JLabel();
        plantillasComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        createAgentJLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        createAgentJLabel.setText("Crear Agente");

        nombrePJLabel.setText("Nombre");

        descriptionPJLabel.setText("Descripcion");

        imageIconJLabel.setText("Imagen Icono");

        roleJLabel.setText("Rol");

        imagenCuerpoEnteroJLabel.setText("Imagen Cuerpo Entero");

        nameAgentJTextField.setText("");

        descriptionAgenJTextField.setText("");

        iconJTextField.setText("");

        roleJTextField.setText("");

        imageCuerpoEnteroJTextField.setText("");

        habilitiesJLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        habilitiesJLabel.setText("Habilidades");

        hability1JLabel.setText("Habilidad 1");

        hability2JLabel.setText("Habilidad 2");

        hability3JLabel.setText("Habilidad 3");

        hability4JLabel.setText("Habilidad 4");

        nameHabilidad1.setText("Nombre");

        descriptionHabilidad1.setText("Descripcion");

        descriptionHabilidad2.setText("Descripcion");

        nameHabilidad2.setText("Nombre");

        nameHabilidad3.setText("Nombre");

        descriptionHabilidad3.setText("Descripcion");

        nameHabilidad4.setText("Nombre");

        descriptionHabilidad4.setText("Descripcion");

        nameHability1JTextField.setText("");

        nameHability3JTextField.setText("");

        nameHability2JTextField.setText("");

        nameHability4JTextField.setText("");

        descriptionHability1JTextField.setText("");

        descriptionHability2JTextField.setText("");

        descriptionHability3JTextField.setText("");

        descriptionHability4JTextField.setText("");

        createJButton.setText("Crear");

        cancelJButton.setText("Cancelar");
        cancelJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelJButtonActionPerformed(evt);
            }
        });

        plantillaJLabel.setText("Elige si lo prefieres una de las plantillas prehechas");

        plantillasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sin plantilla" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(plantillaJLabel)
                                .addGap(18, 18, 18)
                                .addComponent(plantillasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(descriptionPJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(nombrePJLabel)
                                        .addComponent(imageIconJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(roleJLabel)
                                    .addComponent(imagenCuerpoEnteroJLabel)
                                    .addComponent(hability1JLabel)
                                    .addComponent(hability2JLabel)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descriptionHabilidad1)
                                            .addComponent(nameHabilidad2)
                                            .addComponent(descriptionHabilidad2)
                                            .addComponent(nameHabilidad1))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(nameAgentJTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                                            .addComponent(descriptionAgenJTextField)
                                            .addComponent(iconJTextField)
                                            .addComponent(roleJTextField)
                                            .addComponent(imageCuerpoEnteroJTextField)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(nameHability2JTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                            .addComponent(descriptionHability1JTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(descriptionHability2JTextField)
                                            .addComponent(nameHability1JTextField, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(descriptionHabilidad3)
                                                    .addComponent(nameHabilidad3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(nameHability3JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                                    .addComponent(descriptionHability3JTextField)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(createJButton)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cancelJButton))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(hability4JLabel)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(nameHabilidad4)
                                                                    .addComponent(descriptionHabilidad4))))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                            .addComponent(nameHability4JTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                                            .addComponent(descriptionHability4JTextField)))
                                                    .addComponent(hability3JLabel)))))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(createAgentJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(habilitiesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createAgentJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plantillaJLabel)
                    .addComponent(plantillasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrePJLabel)
                    .addComponent(nameAgentJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(descriptionAgenJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descriptionPJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roleJLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(iconJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(imageIconJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(roleJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageCuerpoEnteroJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(imagenCuerpoEnteroJLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(habilitiesJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hability1JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameHabilidad1)
                            .addComponent(nameHability1JTextField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionHabilidad1)
                            .addComponent(descriptionHability1JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(hability2JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameHabilidad2)
                            .addComponent(nameHability2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionHabilidad2)
                            .addComponent(descriptionHability2JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hability3JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameHabilidad3)
                            .addComponent(nameHability3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionHabilidad3)
                            .addComponent(descriptionHability3JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(hability4JLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameHabilidad4)
                            .addComponent(nameHability4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(descriptionHabilidad4)
                            .addComponent(descriptionHability4JTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createJButton)
                    .addComponent(cancelJButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cancelJButtonActionPerformed
    
    private void fixJTextField(){
        JTextField[] fields = {this.nameAgentJTextField, this.descriptionAgenJTextField, this.iconJTextField, this.roleJTextField, this.imageCuerpoEnteroJTextField, this.nameHability1JTextField, this.nameHability2JTextField, this.nameHability3JTextField, this.nameHability4JTextField, this.descriptionHability1JTextField, this.descriptionHability2JTextField, this.descriptionHability3JTextField, this.descriptionHability4JTextField};
        Dimension fix = new Dimension(208,22);
        
        for(JTextField field : fields){
            field.setPreferredSize(fix);
            field.setMaximumSize(fix);
        }
    }
    
    public void enableDisablePlantillaJLabel(Boolean enableDisable){
        this.plantillaJLabel.setEnabled(enableDisable);
        this.plantillaJLabel.setVisible(enableDisable);
    }
    public void enableDisableComboBoxPlantilla(Boolean enableDisable){
        this.plantillasComboBox.setEnabled(enableDisable);
        this.plantillasComboBox.setVisible(enableDisable);
    }
            
    public void setTitleCreateAndEditJLabel(String s){
        this.createAgentJLabel.setText(s);
    }
    public void setTextCrearJButton(String s){
        this.createJButton.setText(s);
    }
    
    public String getNameAgent() {
        return this.nameAgentJTextField.getText();
    }

    public String getDescriptionAgent() {
        return this.descriptionAgenJTextField.getText();
    }

    public String getImageIconSmallFace() {
        return this.iconJTextField.getText();
    }

    public String getImageDisplay() {
        return this.imageCuerpoEnteroJTextField.getText();
    }

    public String getRole() {
        return this.roleJTextField.getText();
    }

    public String getNameHability1() {
        return this.nameHability1JTextField.getText();
    }

    public String getDescriptionHability1() {
        return this.descriptionHability1JTextField.getText();
    }

    public String getNameHability2() {
        return this.nameHability2JTextField.getText();
    }

    public String getDescriptionHability2() {
        return this.descriptionHability2JTextField.getText();
    }

    public String getNameHability3() {
        return this.nameHability3JTextField.getText();
    }

    public String getDescriptionHability3() {
        return this.descriptionHability3JTextField.getText();
    }

    public String getNameHability4() {
        return this.nameHability4JTextField.getText();
    }

    public String getDescriptionHability4() {
        return this.descriptionHability4JTextField.getText();
    }

    public void setCreateButtonActionListener(ActionListener al) {
        this.createJButton.addActionListener(al);
    }

    public void setCancelButtonActionListener(ActionListener al) {
        this.cancelJButton.addActionListener(al);
    }

    public void setNameAgent(String nameAgent) {
        this.nameAgentJTextField.setText(nameAgent);
    }

    public void setDescriptionAgent(String descriptionAgent) {
        this.descriptionAgenJTextField.setText(descriptionAgent);
    }

    public void setImageIconSmallFace(String imageIconSmallFace) {
        this.iconJTextField.setText(imageIconSmallFace);
    }

    public void setImageDisplay(String imageDisplay) {
        this.imageCuerpoEnteroJTextField.setText(imageDisplay);
    }

    public void setRole(String role) {
        this.roleJTextField.setText(role);
    }

    public void setNameHability1(String nameHability1) {
        this.nameHability1JTextField.setText(nameHability1);
    }

    public void setDescriptionHability1(String descriptionHability1) {
        this.descriptionHability1JTextField.setText(descriptionHability1);
    }

    public void setNameHability2(String nameHability2) {
        this.nameHability2JTextField.setText(nameHability2);
    }

    public void setDescriptionHability2(String descriptionHability2) {
        this.descriptionHability2JTextField.setText(descriptionHability2);
    }

    public void setNameHability3(String nameHability3) {
        this.nameHability3JTextField.setText(nameHability3);
    }

    public void setDescriptionHability3(String descriptionHability3) {
        this.descriptionHability3JTextField.setText(descriptionHability3);
    }

    public void setNameHability4(String nameHability4) {
        this.nameHability4JTextField.setText(nameHability4);
    }

    public void setDescriptionHability4(String descriptionHability4) {
        this.descriptionHability4JTextField.setText(descriptionHability4);
    }
    
    public String getItemComBox(){
        return this.plantillasComboBox.getSelectedItem().toString();
    }
    public void addItemPlantillaComboBox(String plantilla){
        this.plantillasComboBox.addItem(plantilla);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelJButton;
    private javax.swing.JLabel createAgentJLabel;
    private javax.swing.JButton createJButton;
    private javax.swing.JTextField descriptionAgenJTextField;
    private javax.swing.JLabel descriptionHabilidad1;
    private javax.swing.JLabel descriptionHabilidad2;
    private javax.swing.JLabel descriptionHabilidad3;
    private javax.swing.JLabel descriptionHabilidad4;
    private javax.swing.JTextField descriptionHability1JTextField;
    private javax.swing.JTextField descriptionHability2JTextField;
    private javax.swing.JTextField descriptionHability3JTextField;
    private javax.swing.JTextField descriptionHability4JTextField;
    private javax.swing.JLabel descriptionPJLabel;
    private javax.swing.JLabel habilitiesJLabel;
    private javax.swing.JLabel hability1JLabel;
    private javax.swing.JLabel hability2JLabel;
    private javax.swing.JLabel hability3JLabel;
    private javax.swing.JLabel hability4JLabel;
    private javax.swing.JTextField iconJTextField;
    private javax.swing.JTextField imageCuerpoEnteroJTextField;
    private javax.swing.JLabel imageIconJLabel;
    private javax.swing.JLabel imagenCuerpoEnteroJLabel;
    private javax.swing.JTextField nameAgentJTextField;
    private javax.swing.JLabel nameHabilidad1;
    private javax.swing.JLabel nameHabilidad2;
    private javax.swing.JLabel nameHabilidad3;
    private javax.swing.JLabel nameHabilidad4;
    private javax.swing.JTextField nameHability1JTextField;
    private javax.swing.JTextField nameHability2JTextField;
    private javax.swing.JTextField nameHability3JTextField;
    private javax.swing.JTextField nameHability4JTextField;
    private javax.swing.JLabel nombrePJLabel;
    private javax.swing.JLabel plantillaJLabel;
    private javax.swing.JComboBox<String> plantillasComboBox;
    private javax.swing.JLabel roleJLabel;
    private javax.swing.JTextField roleJTextField;
    // End of variables declaration//GEN-END:variables
}
