/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.ActionListener;

/**
 *
 * @author dam2_alu05@inf.ald
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form Screen
     */
    public MainJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        registerJButton = new javax.swing.JButton();
        loginJButton = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        descripcionLabel = new javax.swing.JLabel();
        habilidadesLabel = new javax.swing.JLabel();
        imagenhabilidad1Label = new javax.swing.JLabel();
        nombrehabilidad1Label = new javax.swing.JLabel();
        descripcionhabilidad1Label = new javax.swing.JLabel();
        imagenhabilidad2Label = new javax.swing.JLabel();
        nombrehabilidad2Label = new javax.swing.JLabel();
        descripcionhabilidad2Label = new javax.swing.JLabel();
        imagenhabilidad3Label = new javax.swing.JLabel();
        nombrehabilidad3Label = new javax.swing.JLabel();
        descripcionhabilidad3Label = new javax.swing.JLabel();
        imagenhabilidad4Label = new javax.swing.JLabel();
        nombrehabilidad4Label = new javax.swing.JLabel();
        descripcionhabilidad4Label = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        showJButton = new javax.swing.JButton();
        returnJButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Inter Regular", 1, 36)); // NOI18N
        jLabel1.setText("ValorantApi");

        searchTextField.setText("Busqueda");
        searchTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextFieldActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rol", "Duelista", "Controlador", "Centinela", "Iniciador", " " }));
        jComboBox1.setSelectedItem(Rol);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        registerJButton.setText("Registrarse");
        registerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerJButtonActionPerformed(evt);
            }
        });

        loginJButton.setText("Login");

        jLayeredPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 305, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 0));

        descripcionLabel.setText("Descripcion");

        habilidadesLabel.setText("Habilidades");

        imagenhabilidad1Label.setText("Imagen");

        nombrehabilidad1Label.setText("Nombre:");

        descripcionhabilidad1Label.setText("Descripcion");

        imagenhabilidad2Label.setText("Imagen");

        nombrehabilidad2Label.setText("Nombre:");

        descripcionhabilidad2Label.setText("Descripcion");

        imagenhabilidad3Label.setText("Imagen");

        nombrehabilidad3Label.setText("Nombre:");

        descripcionhabilidad3Label.setText("Descripcion");

        imagenhabilidad4Label.setText("Imagen");

        nombrehabilidad4Label.setText("Nombre:");

        descripcionhabilidad4Label.setText("Descripcion");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenhabilidad1Label)
                            .addComponent(imagenhabilidad2Label)
                            .addComponent(imagenhabilidad3Label)
                            .addComponent(imagenhabilidad4Label))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombrehabilidad1Label)
                            .addComponent(nombrehabilidad2Label)
                            .addComponent(nombrehabilidad3Label)
                            .addComponent(nombrehabilidad4Label))
                        .addGap(77, 77, 77)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descripcionhabilidad4Label)
                            .addComponent(descripcionhabilidad3Label)
                            .addComponent(descripcionhabilidad2Label)
                            .addComponent(descripcionhabilidad1Label)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descripcionLabel)
                            .addComponent(habilidadesLabel))))
                .addContainerGap(161, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(descripcionLabel)
                .addGap(18, 18, 18)
                .addComponent(habilidadesLabel)
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombrehabilidad1Label)
                    .addComponent(imagenhabilidad1Label)
                    .addComponent(descripcionhabilidad1Label))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenhabilidad2Label)
                    .addComponent(nombrehabilidad2Label)
                    .addComponent(descripcionhabilidad2Label))
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenhabilidad3Label)
                    .addComponent(nombrehabilidad3Label)
                    .addComponent(descripcionhabilidad3Label))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagenhabilidad4Label)
                    .addComponent(nombrehabilidad4Label)
                    .addComponent(descripcionhabilidad4Label))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        showJButton.setText("Ver");

        returnJButton.setText("Volver");
        returnJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(showJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(returnJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnJButton)
                    .addComponent(showJButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(registerJButton)
                        .addGap(18, 18, 18)
                        .addComponent(loginJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(316, 316, 316))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerJButton)
                    .addComponent(loginJButton))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLayeredPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextFieldActionPerformed

    private void registerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_registerJButtonActionPerformed

    private void returnJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnJButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    public void setRegisterJButtonActionListener(ActionListener al){
        this.registerJButton.addActionListener(al);
    }
    
    public void setLoginJButtonActionListener(ActionListener al){
        this.loginJButton.addActionListener(al);
    }
    
    public void setShowJButtonActionListener(ActionListener al){
        this.showJButton.addActionListener(al);
    }
    
    public void setReturnJButtonActionListener(ActionListener al){
        this.returnJButton.addActionListener(al);
    }
    
    public String getSearchTextField(){
        return searchTextField.getText();
    }
    
    public void setSearchTextField(String search){
        searchTextField.setText(search);
    }
    
    public void setImagenhabilidad1Label(){
        this.imagenhabilidad1Label.setIcon(icon);
    }
    
    public void setNombrehabilidad1Label(){
        this.nombrehabilidad1Label.setText(text);
    }
    
    public void setDescripcionhabilidad1Label(){
        this.descripcionhabilidad1Label.setText(text);
    }
    
    public void setImagenhabilidad2Label(){
        this.imagenhabilidad2Label.setIcon(icon);
    }
    
    public void setNombrehabilidad2Label(){
        this.nombrehabilidad2Label.setText(text);
    }
    
    public void setDescripcionhabilidad2Label(){
        this.descripcionhabilidad2Label.setText(text);
    }
    
    public void setImagenhabilidad3Label(){
        this.imagenhabilidad3Label.setIcon(icon);
    }
    
    public void setNombrehabilidad3Label(){
        this.nombrehabilidad3Label.setText(text);
    }
    
    public void setDescripcionhabilidad3Label(){
        this.descripcionhabilidad3Label.setText(text);
    }
    
    public void setImagenhabilidad4Label(){
        this.imagenhabilidad4Label.setIcon(icon);
    }
    
    public void setNombrehabilidad4Label(){
        this.nombrehabilidad4Label.setText(text);
    }
    
    public void setDescripcionhabilidad4Label(){
        this.descripcionhabilidad4Label.setText(text);
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descripcionLabel;
    private javax.swing.JLabel descripcionhabilidad1Label;
    private javax.swing.JLabel descripcionhabilidad2Label;
    private javax.swing.JLabel descripcionhabilidad3Label;
    private javax.swing.JLabel descripcionhabilidad4Label;
    private javax.swing.JLabel habilidadesLabel;
    private javax.swing.JLabel imagenhabilidad1Label;
    private javax.swing.JLabel imagenhabilidad2Label;
    private javax.swing.JLabel imagenhabilidad3Label;
    private javax.swing.JLabel imagenhabilidad4Label;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton loginJButton;
    private javax.swing.JLabel nombrehabilidad1Label;
    private javax.swing.JLabel nombrehabilidad2Label;
    private javax.swing.JLabel nombrehabilidad3Label;
    private javax.swing.JLabel nombrehabilidad4Label;
    private javax.swing.JButton registerJButton;
    private javax.swing.JButton returnJButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton showJButton;
    // End of variables declaration//GEN-END:variables
}
